// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/model/proto/message_schema.proto

package model.proto;

public final class SearchModel {
  private SearchModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributed.search.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string search_query = 1;</code>
     * @return Whether the searchQuery field is set.
     */
    boolean hasSearchQuery();
    /**
     * <code>required string search_query = 1;</code>
     * @return The searchQuery.
     */
    String getSearchQuery();
    /**
     * <code>required string search_query = 1;</code>
     * @return The bytes for searchQuery.
     */
    com.google.protobuf.ByteString
        getSearchQueryBytes();
  }
  /**
   * Protobuf type {@code distributed.search.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:distributed.search.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      searchQuery_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Request();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              searchQuery_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchModel.internal_static_distributed_search_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchModel.internal_static_distributed_search_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Request.class, Builder.class);
    }

    private int bitField0_;
    public static final int SEARCH_QUERY_FIELD_NUMBER = 1;
    private volatile Object searchQuery_;
    /**
     * <code>required string search_query = 1;</code>
     * @return Whether the searchQuery field is set.
     */
    @Override
    public boolean hasSearchQuery() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string search_query = 1;</code>
     * @return The searchQuery.
     */
    @Override
    public String getSearchQuery() {
      Object ref = searchQuery_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          searchQuery_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string search_query = 1;</code>
     * @return The bytes for searchQuery.
     */
    @Override
    public com.google.protobuf.ByteString
        getSearchQueryBytes() {
      Object ref = searchQuery_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        searchQuery_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSearchQuery()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, searchQuery_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, searchQuery_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Request)) {
        return super.equals(obj);
      }
      Request other = (Request) obj;

      if (hasSearchQuery() != other.hasSearchQuery()) return false;
      if (hasSearchQuery()) {
        if (!getSearchQuery()
            .equals(other.getSearchQuery())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSearchQuery()) {
        hash = (37 * hash) + SEARCH_QUERY_FIELD_NUMBER;
        hash = (53 * hash) + getSearchQuery().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributed.search.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributed.search.Request)
        RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchModel.internal_static_distributed_search_Request_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchModel.internal_static_distributed_search_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
      }

      // Construct using model.proto.SearchModel.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        searchQuery_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchModel.internal_static_distributed_search_Request_descriptor;
      }

      @Override
      public Request getDefaultInstanceForType() {
        return Request.getDefaultInstance();
      }

      @Override
      public Request build() {
        Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Request buildPartial() {
        Request result = new Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.searchQuery_ = searchQuery_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Request) {
          return mergeFrom((Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Request other) {
        if (other == Request.getDefaultInstance()) return this;
        if (other.hasSearchQuery()) {
          bitField0_ |= 0x00000001;
          searchQuery_ = other.searchQuery_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasSearchQuery()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object searchQuery_ = "";
      /**
       * <code>required string search_query = 1;</code>
       * @return Whether the searchQuery field is set.
       */
      public boolean hasSearchQuery() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string search_query = 1;</code>
       * @return The searchQuery.
       */
      public String getSearchQuery() {
        Object ref = searchQuery_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            searchQuery_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string search_query = 1;</code>
       * @return The bytes for searchQuery.
       */
      public com.google.protobuf.ByteString
          getSearchQueryBytes() {
        Object ref = searchQuery_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          searchQuery_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string search_query = 1;</code>
       * @param value The searchQuery to set.
       * @return This builder for chaining.
       */
      public Builder setSearchQuery(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        searchQuery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string search_query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSearchQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        searchQuery_ = getDefaultInstance().getSearchQuery();
        onChanged();
        return this;
      }
      /**
       * <code>required string search_query = 1;</code>
       * @param value The bytes for searchQuery to set.
       * @return This builder for chaining.
       */
      public Builder setSearchQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        searchQuery_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:distributed.search.Request)
    }

    // @@protoc_insertion_point(class_scope:distributed.search.Request)
    private static final Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @Override
    public Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributed.search.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    java.util.List<Response.DocumentStats>
        getResultDocumentsList();
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    Response.DocumentStats getResultDocuments(int index);
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    int getResultDocumentsCount();
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    java.util.List<? extends Response.DocumentStatsOrBuilder>
        getResultDocumentsOrBuilderList();
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    Response.DocumentStatsOrBuilder getResultDocumentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code distributed.search.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:distributed.search.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      resultDocuments_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                resultDocuments_ = new java.util.ArrayList<DocumentStats>();
                mutable_bitField0_ |= 0x00000001;
              }
              resultDocuments_.add(
                  input.readMessage(DocumentStats.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          resultDocuments_ = java.util.Collections.unmodifiableList(resultDocuments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchModel.internal_static_distributed_search_Response_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchModel.internal_static_distributed_search_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Builder.class);
    }

    public interface DocumentStatsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:distributed.search.Response.DocumentStats)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string document_name = 1;</code>
       * @return Whether the documentName field is set.
       */
      boolean hasDocumentName();
      /**
       * <code>required string document_name = 1;</code>
       * @return The documentName.
       */
      String getDocumentName();
      /**
       * <code>required string document_name = 1;</code>
       * @return The bytes for documentName.
       */
      com.google.protobuf.ByteString
          getDocumentNameBytes();

      /**
       * <code>optional double score = 2;</code>
       * @return Whether the score field is set.
       */
      boolean hasScore();
      /**
       * <code>optional double score = 2;</code>
       * @return The score.
       */
      double getScore();

      /**
       * <code>optional int64 document_size = 3;</code>
       * @return Whether the documentSize field is set.
       */
      boolean hasDocumentSize();
      /**
       * <code>optional int64 document_size = 3;</code>
       * @return The documentSize.
       */
      long getDocumentSize();

      /**
       * <code>optional string author_name = 4;</code>
       * @return Whether the authorName field is set.
       */
      boolean hasAuthorName();
      /**
       * <code>optional string author_name = 4;</code>
       * @return The authorName.
       */
      String getAuthorName();
      /**
       * <code>optional string author_name = 4;</code>
       * @return The bytes for authorName.
       */
      com.google.protobuf.ByteString
          getAuthorNameBytes();
    }
    /**
     * Protobuf type {@code distributed.search.Response.DocumentStats}
     */
    public static final class DocumentStats extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:distributed.search.Response.DocumentStats)
        DocumentStatsOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DocumentStats.newBuilder() to construct.
      private DocumentStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DocumentStats() {
        documentName_ = "";
        authorName_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new DocumentStats();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DocumentStats(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                documentName_ = bs;
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                score_ = input.readDouble();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                documentSize_ = input.readInt64();
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                authorName_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchModel.internal_static_distributed_search_Response_DocumentStats_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchModel.internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DocumentStats.class, Builder.class);
      }

      private int bitField0_;
      public static final int DOCUMENT_NAME_FIELD_NUMBER = 1;
      private volatile Object documentName_;
      /**
       * <code>required string document_name = 1;</code>
       * @return Whether the documentName field is set.
       */
      @Override
      public boolean hasDocumentName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string document_name = 1;</code>
       * @return The documentName.
       */
      @Override
      public String getDocumentName() {
        Object ref = documentName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            documentName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string document_name = 1;</code>
       * @return The bytes for documentName.
       */
      @Override
      public com.google.protobuf.ByteString
          getDocumentNameBytes() {
        Object ref = documentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          documentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SCORE_FIELD_NUMBER = 2;
      private double score_;
      /**
       * <code>optional double score = 2;</code>
       * @return Whether the score field is set.
       */
      @Override
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional double score = 2;</code>
       * @return The score.
       */
      @Override
      public double getScore() {
        return score_;
      }

      public static final int DOCUMENT_SIZE_FIELD_NUMBER = 3;
      private long documentSize_;
      /**
       * <code>optional int64 document_size = 3;</code>
       * @return Whether the documentSize field is set.
       */
      @Override
      public boolean hasDocumentSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 document_size = 3;</code>
       * @return The documentSize.
       */
      @Override
      public long getDocumentSize() {
        return documentSize_;
      }

      public static final int AUTHOR_NAME_FIELD_NUMBER = 4;
      private volatile Object authorName_;
      /**
       * <code>optional string author_name = 4;</code>
       * @return Whether the authorName field is set.
       */
      @Override
      public boolean hasAuthorName() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string author_name = 4;</code>
       * @return The authorName.
       */
      @Override
      public String getAuthorName() {
        Object ref = authorName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            authorName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string author_name = 4;</code>
       * @return The bytes for authorName.
       */
      @Override
      public com.google.protobuf.ByteString
          getAuthorNameBytes() {
        Object ref = authorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          authorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDocumentName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, documentName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeDouble(2, score_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeInt64(3, documentSize_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authorName_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, documentName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, score_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, documentSize_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authorName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof DocumentStats)) {
          return super.equals(obj);
        }
        DocumentStats other = (DocumentStats) obj;

        if (hasDocumentName() != other.hasDocumentName()) return false;
        if (hasDocumentName()) {
          if (!getDocumentName()
              .equals(other.getDocumentName())) return false;
        }
        if (hasScore() != other.hasScore()) return false;
        if (hasScore()) {
          if (Double.doubleToLongBits(getScore())
              != Double.doubleToLongBits(
                  other.getScore())) return false;
        }
        if (hasDocumentSize() != other.hasDocumentSize()) return false;
        if (hasDocumentSize()) {
          if (getDocumentSize()
              != other.getDocumentSize()) return false;
        }
        if (hasAuthorName() != other.hasAuthorName()) return false;
        if (hasAuthorName()) {
          if (!getAuthorName()
              .equals(other.getAuthorName())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasDocumentName()) {
          hash = (37 * hash) + DOCUMENT_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getDocumentName().hashCode();
        }
        if (hasScore()) {
          hash = (37 * hash) + SCORE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getScore()));
        }
        if (hasDocumentSize()) {
          hash = (37 * hash) + DOCUMENT_SIZE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getDocumentSize());
        }
        if (hasAuthorName()) {
          hash = (37 * hash) + AUTHOR_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getAuthorName().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static DocumentStats parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DocumentStats parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DocumentStats parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DocumentStats parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DocumentStats parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DocumentStats parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DocumentStats parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DocumentStats parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static DocumentStats parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static DocumentStats parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static DocumentStats parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DocumentStats parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(DocumentStats prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code distributed.search.Response.DocumentStats}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:distributed.search.Response.DocumentStats)
          DocumentStatsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SearchModel.internal_static_distributed_search_Response_DocumentStats_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SearchModel.internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DocumentStats.class, Builder.class);
        }

        // Construct using model.proto.SearchModel.Response.DocumentStats.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          documentName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          score_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          documentSize_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          authorName_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SearchModel.internal_static_distributed_search_Response_DocumentStats_descriptor;
        }

        @Override
        public DocumentStats getDefaultInstanceForType() {
          return DocumentStats.getDefaultInstance();
        }

        @Override
        public DocumentStats build() {
          DocumentStats result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public DocumentStats buildPartial() {
          DocumentStats result = new DocumentStats(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.documentName_ = documentName_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.score_ = score_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.documentSize_ = documentSize_;
            to_bitField0_ |= 0x00000004;
          }
          if (((from_bitField0_ & 0x00000008) != 0)) {
            to_bitField0_ |= 0x00000008;
          }
          result.authorName_ = authorName_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DocumentStats) {
            return mergeFrom((DocumentStats)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DocumentStats other) {
          if (other == DocumentStats.getDefaultInstance()) return this;
          if (other.hasDocumentName()) {
            bitField0_ |= 0x00000001;
            documentName_ = other.documentName_;
            onChanged();
          }
          if (other.hasScore()) {
            setScore(other.getScore());
          }
          if (other.hasDocumentSize()) {
            setDocumentSize(other.getDocumentSize());
          }
          if (other.hasAuthorName()) {
            bitField0_ |= 0x00000008;
            authorName_ = other.authorName_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          if (!hasDocumentName()) {
            return false;
          }
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DocumentStats parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DocumentStats) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private Object documentName_ = "";
        /**
         * <code>required string document_name = 1;</code>
         * @return Whether the documentName field is set.
         */
        public boolean hasDocumentName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string document_name = 1;</code>
         * @return The documentName.
         */
        public String getDocumentName() {
          Object ref = documentName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              documentName_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string document_name = 1;</code>
         * @return The bytes for documentName.
         */
        public com.google.protobuf.ByteString
            getDocumentNameBytes() {
          Object ref = documentName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            documentName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string document_name = 1;</code>
         * @param value The documentName to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          documentName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string document_name = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearDocumentName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          documentName_ = getDefaultInstance().getDocumentName();
          onChanged();
          return this;
        }
        /**
         * <code>required string document_name = 1;</code>
         * @param value The bytes for documentName to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          documentName_ = value;
          onChanged();
          return this;
        }

        private double score_ ;
        /**
         * <code>optional double score = 2;</code>
         * @return Whether the score field is set.
         */
        @Override
        public boolean hasScore() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional double score = 2;</code>
         * @return The score.
         */
        @Override
        public double getScore() {
          return score_;
        }
        /**
         * <code>optional double score = 2;</code>
         * @param value The score to set.
         * @return This builder for chaining.
         */
        public Builder setScore(double value) {
          bitField0_ |= 0x00000002;
          score_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double score = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearScore() {
          bitField0_ = (bitField0_ & ~0x00000002);
          score_ = 0D;
          onChanged();
          return this;
        }

        private long documentSize_ ;
        /**
         * <code>optional int64 document_size = 3;</code>
         * @return Whether the documentSize field is set.
         */
        @Override
        public boolean hasDocumentSize() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>optional int64 document_size = 3;</code>
         * @return The documentSize.
         */
        @Override
        public long getDocumentSize() {
          return documentSize_;
        }
        /**
         * <code>optional int64 document_size = 3;</code>
         * @param value The documentSize to set.
         * @return This builder for chaining.
         */
        public Builder setDocumentSize(long value) {
          bitField0_ |= 0x00000004;
          documentSize_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 document_size = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearDocumentSize() {
          bitField0_ = (bitField0_ & ~0x00000004);
          documentSize_ = 0L;
          onChanged();
          return this;
        }

        private Object authorName_ = "";
        /**
         * <code>optional string author_name = 4;</code>
         * @return Whether the authorName field is set.
         */
        public boolean hasAuthorName() {
          return ((bitField0_ & 0x00000008) != 0);
        }
        /**
         * <code>optional string author_name = 4;</code>
         * @return The authorName.
         */
        public String getAuthorName() {
          Object ref = authorName_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              authorName_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string author_name = 4;</code>
         * @return The bytes for authorName.
         */
        public com.google.protobuf.ByteString
            getAuthorNameBytes() {
          Object ref = authorName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            authorName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string author_name = 4;</code>
         * @param value The authorName to set.
         * @return This builder for chaining.
         */
        public Builder setAuthorName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          authorName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string author_name = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearAuthorName() {
          bitField0_ = (bitField0_ & ~0x00000008);
          authorName_ = getDefaultInstance().getAuthorName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string author_name = 4;</code>
         * @param value The bytes for authorName to set.
         * @return This builder for chaining.
         */
        public Builder setAuthorNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          authorName_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:distributed.search.Response.DocumentStats)
      }

      // @@protoc_insertion_point(class_scope:distributed.search.Response.DocumentStats)
      private static final DocumentStats DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new DocumentStats();
      }

      public static DocumentStats getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @Deprecated public static final com.google.protobuf.Parser<DocumentStats>
          PARSER = new com.google.protobuf.AbstractParser<DocumentStats>() {
        @Override
        public DocumentStats parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DocumentStats(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DocumentStats> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<DocumentStats> getParserForType() {
        return PARSER;
      }

      @Override
      public DocumentStats getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int RESULT_DOCUMENTS_FIELD_NUMBER = 1;
    private java.util.List<DocumentStats> resultDocuments_;
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    @Override
    public java.util.List<DocumentStats> getResultDocumentsList() {
      return resultDocuments_;
    }
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    @Override
    public java.util.List<? extends DocumentStatsOrBuilder>
        getResultDocumentsOrBuilderList() {
      return resultDocuments_;
    }
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    @Override
    public int getResultDocumentsCount() {
      return resultDocuments_.size();
    }
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    @Override
    public DocumentStats getResultDocuments(int index) {
      return resultDocuments_.get(index);
    }
    /**
     * <pre>
     * the desc sorted list of result documents
     * </pre>
     *
     * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
     */
    @Override
    public DocumentStatsOrBuilder getResultDocumentsOrBuilder(
        int index) {
      return resultDocuments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getResultDocumentsCount(); i++) {
        if (!getResultDocuments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < resultDocuments_.size(); i++) {
        output.writeMessage(1, resultDocuments_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < resultDocuments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, resultDocuments_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Response)) {
        return super.equals(obj);
      }
      Response other = (Response) obj;

      if (!getResultDocumentsList()
          .equals(other.getResultDocumentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultDocumentsCount() > 0) {
        hash = (37 * hash) + RESULT_DOCUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultDocumentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributed.search.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributed.search.Response)
        ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchModel.internal_static_distributed_search_Response_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchModel.internal_static_distributed_search_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.class, Builder.class);
      }

      // Construct using model.proto.SearchModel.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultDocumentsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (resultDocumentsBuilder_ == null) {
          resultDocuments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultDocumentsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchModel.internal_static_distributed_search_Response_descriptor;
      }

      @Override
      public Response getDefaultInstanceForType() {
        return Response.getDefaultInstance();
      }

      @Override
      public Response build() {
        Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Response buildPartial() {
        Response result = new Response(this);
        int from_bitField0_ = bitField0_;
        if (resultDocumentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            resultDocuments_ = java.util.Collections.unmodifiableList(resultDocuments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.resultDocuments_ = resultDocuments_;
        } else {
          result.resultDocuments_ = resultDocumentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Response) {
          return mergeFrom((Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Response other) {
        if (other == Response.getDefaultInstance()) return this;
        if (resultDocumentsBuilder_ == null) {
          if (!other.resultDocuments_.isEmpty()) {
            if (resultDocuments_.isEmpty()) {
              resultDocuments_ = other.resultDocuments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultDocumentsIsMutable();
              resultDocuments_.addAll(other.resultDocuments_);
            }
            onChanged();
          }
        } else {
          if (!other.resultDocuments_.isEmpty()) {
            if (resultDocumentsBuilder_.isEmpty()) {
              resultDocumentsBuilder_.dispose();
              resultDocumentsBuilder_ = null;
              resultDocuments_ = other.resultDocuments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultDocumentsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultDocumentsFieldBuilder() : null;
            } else {
              resultDocumentsBuilder_.addAllMessages(other.resultDocuments_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        for (int i = 0; i < getResultDocumentsCount(); i++) {
          if (!getResultDocuments(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DocumentStats> resultDocuments_ =
        java.util.Collections.emptyList();
      private void ensureResultDocumentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          resultDocuments_ = new java.util.ArrayList<DocumentStats>(resultDocuments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DocumentStats, DocumentStats.Builder, DocumentStatsOrBuilder> resultDocumentsBuilder_;

      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public java.util.List<DocumentStats> getResultDocumentsList() {
        if (resultDocumentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resultDocuments_);
        } else {
          return resultDocumentsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public int getResultDocumentsCount() {
        if (resultDocumentsBuilder_ == null) {
          return resultDocuments_.size();
        } else {
          return resultDocumentsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public DocumentStats getResultDocuments(int index) {
        if (resultDocumentsBuilder_ == null) {
          return resultDocuments_.get(index);
        } else {
          return resultDocumentsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder setResultDocuments(
          int index, DocumentStats value) {
        if (resultDocumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultDocumentsIsMutable();
          resultDocuments_.set(index, value);
          onChanged();
        } else {
          resultDocumentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder setResultDocuments(
          int index, DocumentStats.Builder builderForValue) {
        if (resultDocumentsBuilder_ == null) {
          ensureResultDocumentsIsMutable();
          resultDocuments_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultDocumentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder addResultDocuments(DocumentStats value) {
        if (resultDocumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultDocumentsIsMutable();
          resultDocuments_.add(value);
          onChanged();
        } else {
          resultDocumentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder addResultDocuments(
          int index, DocumentStats value) {
        if (resultDocumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultDocumentsIsMutable();
          resultDocuments_.add(index, value);
          onChanged();
        } else {
          resultDocumentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder addResultDocuments(
          DocumentStats.Builder builderForValue) {
        if (resultDocumentsBuilder_ == null) {
          ensureResultDocumentsIsMutable();
          resultDocuments_.add(builderForValue.build());
          onChanged();
        } else {
          resultDocumentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder addResultDocuments(
          int index, DocumentStats.Builder builderForValue) {
        if (resultDocumentsBuilder_ == null) {
          ensureResultDocumentsIsMutable();
          resultDocuments_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultDocumentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder addAllResultDocuments(
          Iterable<? extends DocumentStats> values) {
        if (resultDocumentsBuilder_ == null) {
          ensureResultDocumentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, resultDocuments_);
          onChanged();
        } else {
          resultDocumentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder clearResultDocuments() {
        if (resultDocumentsBuilder_ == null) {
          resultDocuments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultDocumentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public Builder removeResultDocuments(int index) {
        if (resultDocumentsBuilder_ == null) {
          ensureResultDocumentsIsMutable();
          resultDocuments_.remove(index);
          onChanged();
        } else {
          resultDocumentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public DocumentStats.Builder getResultDocumentsBuilder(
          int index) {
        return getResultDocumentsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public DocumentStatsOrBuilder getResultDocumentsOrBuilder(
          int index) {
        if (resultDocumentsBuilder_ == null) {
          return resultDocuments_.get(index);  } else {
          return resultDocumentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public java.util.List<? extends DocumentStatsOrBuilder>
           getResultDocumentsOrBuilderList() {
        if (resultDocumentsBuilder_ != null) {
          return resultDocumentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resultDocuments_);
        }
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public DocumentStats.Builder addResultDocumentsBuilder() {
        return getResultDocumentsFieldBuilder().addBuilder(
            DocumentStats.getDefaultInstance());
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public DocumentStats.Builder addResultDocumentsBuilder(
          int index) {
        return getResultDocumentsFieldBuilder().addBuilder(
            index, DocumentStats.getDefaultInstance());
      }
      /**
       * <pre>
       * the desc sorted list of result documents
       * </pre>
       *
       * <code>repeated .distributed.search.Response.DocumentStats result_documents = 1;</code>
       */
      public java.util.List<DocumentStats.Builder>
           getResultDocumentsBuilderList() {
        return getResultDocumentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DocumentStats, DocumentStats.Builder, DocumentStatsOrBuilder>
          getResultDocumentsFieldBuilder() {
        if (resultDocumentsBuilder_ == null) {
          resultDocumentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DocumentStats, DocumentStats.Builder, DocumentStatsOrBuilder>(
                  resultDocuments_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          resultDocuments_ = null;
        }
        return resultDocumentsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:distributed.search.Response)
    }

    // @@protoc_insertion_point(class_scope:distributed.search.Response)
    private static final Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Response();
    }

    public static Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @Override
    public Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_Request_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_Response_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributed_search_Response_DocumentStats_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n.src/main/java/model/proto/message_sche" +
      "ma.proto\022\022distributed.search\"\037\n\007Request\022" +
      "\024\n\014search_query\030\001 \002(\t\"\263\001\n\010Response\022D\n\020re" +
      "sult_documents\030\001 \003(\0132*.distributed.searc" +
      "h.Response.DocumentStats\032a\n\rDocumentStat" +
      "s\022\025\n\rdocument_name\030\001 \002(\t\022\r\n\005score\030\002 \001(\001\022" +
      "\025\n\rdocument_size\030\003 \001(\003\022\023\n\013author_name\030\004 " +
      "\001(\tB\032\n\013model.protoB\013SearchModel"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_distributed_search_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_distributed_search_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_Request_descriptor,
        new String[] { "SearchQuery", });
    internal_static_distributed_search_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_distributed_search_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_Response_descriptor,
        new String[] { "ResultDocuments", });
    internal_static_distributed_search_Response_DocumentStats_descriptor =
      internal_static_distributed_search_Response_descriptor.getNestedTypes().get(0);
    internal_static_distributed_search_Response_DocumentStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_distributed_search_Response_DocumentStats_descriptor,
        new String[] { "DocumentName", "Score", "DocumentSize", "AuthorName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
